import { SubAccount } from "@/components/subaccount/type";

export const MOCK_SUB_ACCOUNTS: SubAccount[] = [
  {
    id: "1",
    name: "Lagos Operations",
    icon: "bank",
    bankName: "Nomba (Titan Trust)",
    accountNumberMasked: "0120****890",
    receivedAmount: 3500000,
    splitPercent: 70,
    code: "ACCT_xz9k1m2p",
    status: "Verified",
  },
  {
    id: "2",
    name: "Partner Collections",
    icon: "users",
    bankName: "GTBank",
    accountNumberMasked: "0231****112",
    receivedAmount: 3500000,
    splitPercent: 20,
    code: "ACCT_ab4c7d8e",
    status: "Verified",
  },
  {
    id: "3",
    name: "VAT Remittance",
    icon: "bank",
    bankName: "FIRS Settlement Account",
    accountNumberMasked: "2001****445",
    receivedAmount: 3500000,
    splitPercent: 7.5,
    code: "ACCT_fg2h5i6j",
    status: "Verified",
  },
  {
    id: "4",
    name: "Marketing Affiliate",
    icon: "speakerphone",
    bankName: "Zenith Bank",
    accountNumberMasked: "1234****567",
    receivedAmount: 3500000,
    splitPercent: 2.5,
    code: "ACCT_qz1m9k2x",
    status: "Unverified",
  },
  {
    id: "5",
    name: "Growth Fund",
    icon: "chart-line",
    bankName: "First Bank",
    accountNumberMasked: "3349****210",
    receivedAmount: 3500000,
    splitPercent: 0,
    code: "ACCT_pv7n3w4r",
    status: "Verified",
  },
];
