import { SubscriptionDetail } from "@/components/subscription/type";

export const MOCK_SUBSCRIPTION_DETAILS: SubscriptionDetail[] = [
  {
    id: "1",
    subscriptionCode: "SUB_hwr0xyn11s2wht2",
    plan: { id: "p1", name: "Ola" },
    subscriber: { name: "Teniola Timothy", email: "teniolatimothy@gmail.com" },
    amount: 1000000,
    interval: "daily",
    status: "Active",
    nextChargeDate: "2026-07-04",
    card: { brand: "visa", last4: "4242", expiryMonth: "12", expiryYear: "27" },
    subscribedOn: "2026-07-01",
    paymentsCompleted: 1,
    paymentsTotal: undefined,
    lifetimeValue: 1000000,
  },
  {
    id: "2",
    subscriptionCode: "SUB_ax92mvqp7t1k",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Chidinma Okafor", email: "chidinma.okafor@yahoo.com" },
    amount: 5000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-08-01",
    card: {
      brand: "mastercard",
      last4: "8891",
      expiryMonth: "03",
      expiryYear: "28",
    },
    subscribedOn: "2026-05-01",
    paymentsCompleted: 3,
    paymentsTotal: 12,
    lifetimeValue: 15000,
  },
  {
    id: "3",
    subscriptionCode: "SUB_bz71ntlq9r4j",
    plan: { id: "p3", name: "Pro" },
    subscriber: { name: "Emeka Nwosu", email: "emeka.nwosu@outlook.com" },
    amount: 25000,
    interval: "monthly",
    status: "Attention",
    nextChargeDate: "2026-07-05",
    card: { brand: "visa", last4: "1029", expiryMonth: "09", expiryYear: "26" },
    subscribedOn: "2026-04-05",
    paymentsCompleted: 2,
    paymentsTotal: 12,
    lifetimeValue: 50000,
  },
  {
    id: "4",
    subscriptionCode: "SUB_cy83oprm2s5h",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Fatima Bello", email: "fatima.bello@gmail.com" },
    amount: 5000,
    interval: "monthly",
    status: "Cancelled",
    nextChargeDate: null,
    card: {
      brand: "verve",
      last4: "7734",
      expiryMonth: "06",
      expiryYear: "27",
    },
    subscribedOn: "2026-02-15",
    paymentsCompleted: 4,
    paymentsTotal: 6,
    lifetimeValue: 20000,
  },
  {
    id: "5",
    subscriptionCode: "SUB_dw94pqsn3t6k",
    plan: { id: "p4", name: "Enterprise" },
    subscriber: { name: "Segun Adeyemi", email: "segun.adeyemi@company.com" },
    amount: 150000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-07-20",
    card: {
      brand: "mastercard",
      last4: "5567",
      expiryMonth: "11",
      expiryYear: "29",
    },
    subscribedOn: "2026-01-20",
    paymentsCompleted: 6,
    paymentsTotal: undefined,
    lifetimeValue: 900000,
  },
  {
    id: "6",
    subscriptionCode: "SUB_ex05qrto4u7l",
    plan: { id: "p3", name: "Pro" },
    subscriber: { name: "Amaka Eze", email: "amaka.eze@gmail.com" },
    amount: 25000,
    interval: "weekly",
    status: "Attention",
    nextChargeDate: "2026-07-10",
    card: { brand: "visa", last4: "3321", expiryMonth: "08", expiryYear: "27" },
    subscribedOn: "2026-06-10",
    paymentsCompleted: 3,
    paymentsTotal: 10,
    lifetimeValue: 75000,
  },
  {
    id: "7",
    subscriptionCode: "SUB_fy16rsup5v8m",
    plan: { id: "p1", name: "Ola" },
    subscriber: { name: "Ibrahim Musa", email: "ibrahim.musa@hotmail.com" },
    amount: 1000000,
    interval: "daily",
    status: "Completed",
    nextChargeDate: null,
    card: { brand: "visa", last4: "9982", expiryMonth: "01", expiryYear: "26" },
    subscribedOn: "2026-06-01",
    paymentsCompleted: 10,
    paymentsTotal: 10,
    lifetimeValue: 10000000,
  },
  {
    id: "8",
    subscriptionCode: "SUB_gz27stvq6w9n",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Blessing Nnamdi", email: "blessing.nnamdi@gmail.com" },
    amount: 5000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-07-30",
    card: {
      brand: "mastercard",
      last4: "4410",
      expiryMonth: "04",
      expiryYear: "28",
    },
    subscribedOn: "2026-06-30",
    paymentsCompleted: 1,
    paymentsTotal: 12,
    lifetimeValue: 5000,
  },
];
