import { Subscription } from "@/components/subscription/type";

export const MOCK_SUBCRIPTION: Subscription[] = [
  {
    id: "1",
    subscriptionCode: "SUB_hwr0xyn11s2wht2",
    plan: { id: "p1", name: "Ola" },
    subscriber: { name: "Teniola Timothy", email: "teniolatimothy@gmail.com" },
    amount: 1000000,
    interval: "daily",
    status: "Active",
    nextChargeDate: "2026-07-04",
  },
  {
    id: "2",
    subscriptionCode: "SUB_ax92mvqp7t1k",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Chidinma Okafor", email: "chidinma.okafor@yahoo.com" },
    amount: 5000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-08-01",
  },
  {
    id: "3",
    subscriptionCode: "SUB_bz71ntlq9r4j",
    plan: { id: "p3", name: "Pro" },
    subscriber: { name: "Emeka Nwosu", email: "emeka.nwosu@outlook.com" },
    amount: 25000,
    interval: "monthly",
    status: "Attention",
    nextChargeDate: "2026-07-05",
  },
  {
    id: "4",
    subscriptionCode: "SUB_cy83oprm2s5h",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Fatima Bello", email: "fatima.bello@gmail.com" },
    amount: 5000,
    interval: "monthly",
    status: "Cancelled",
    nextChargeDate: null,
  },
  {
    id: "5",
    subscriptionCode: "SUB_dw94pqsn3t6k",
    plan: { id: "p4", name: "Enterprise" },
    subscriber: { name: "Segun Adeyemi", email: "segun.adeyemi@company.com" },
    amount: 150000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-07-20",
  },
  {
    id: "6",
    subscriptionCode: "SUB_ex05qrto4u7l",
    plan: { id: "p3", name: "Pro" },
    subscriber: { name: "Amaka Eze", email: "amaka.eze@gmail.com" },
    amount: 25000,
    interval: "weekly",
    status: "Attention",
    nextChargeDate: "2026-07-10",
  },
  {
    id: "7",
    subscriptionCode: "SUB_fy16rsup5v8m",
    plan: { id: "p1", name: "Ola" },
    subscriber: { name: "Ibrahim Musa", email: "ibrahim.musa@hotmail.com" },
    amount: 1000000,
    interval: "daily",
    status: "Completed",
    nextChargeDate: null,
  },
  {
    id: "8",
    subscriptionCode: "SUB_gz27stvq6w9n",
    plan: { id: "p2", name: "Starter" },
    subscriber: { name: "Blessing Nnamdi", email: "blessing.nnamdi@gmail.com" },
    amount: 5000,
    interval: "monthly",
    status: "Active",
    nextChargeDate: "2026-07-30",
  },
];
